### ISSUE TITLE
Direct Linking to Shows Cause an Error

### ISSUE THREAD

**Issue by binerys** [uclaradio/uclaradio#117]
A direct link to a show: https://uclaradio.com/shows/192
Will yield the following error : 
![image](https://cloud.githubusercontent.com/assets/9737156/25916912/294e3f8c-357b-11e7-8f69-8ab9be8fef32.png)

Accessing the show via the schedule is fine

**Comment by binerys** [comment]
@anmol678  If you have the time, can you check this out? It might be related to the inclusion of the djs

**Comment by anmol678** [comment]
Okay so I checked it out and seems like there is an issue if any of the show pages is accessed directly. If you navigate through uclaradio.com/shows to the page for any show then it works which is rather strange. It probably has something to do with the way props are moved around. I'll fix it asap.

**Comment by anmol678** [comment]
It probably has something to do with the way props are passed around. I'll fix it asap.

**Comment by binerys** [comment]
resolved in pull #164
