### ISSUE TITLE
Dependency install error for canvas

### ISSUE THREAD

**Issue by binerys** [uclaradio/uclaradio#131]
## Context
When a new developer attempts to setup their environment, the error pictured below occurs after `yarn dev`. It currently does not affect accessing the frontend.

## Possible Solution
Look into why `canvas` is throwing this issue and what packages have it as a dependency. 

## Screenshot(s) 
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/9737156/29244514-a57e27ec-7f6e-11e7-91f5-a63dd7b4cc6f.png">

## Your Environment 

- [X ] __Desktop__:  Mac

**Comment by nathunsmitty** [comment]
[Canvas seems to be dependent on Cairo](https://www.npmjs.com/package/canvas). [Cairo](https://www.cairographics.org) looks to be a graphics library? I have no idea which packages we're using relies on Canvas, but look at [lines 21–23 of setup.sh](https://github.com/uclaradio/uclaradio/blob/e474813a0b9a297f81ce40543c27d67d715e094a/setup.sh#L21-L23):

```shell
## might have to install cairo for dependent npm packages
# brew install cairo
sudo npm install
```

If we readd the `brew install` line, think it'd work?

**Comment by nathunsmitty** [comment]
__Update:__ pretty sure this is it, I got the same error by running the commands:
```shell
brew uninstall cairo
rm -rf node_modules
yarn
```
