### ISSUE TITLE
Rename .jsx files to .js

### ISSUE THREAD

**Issue by nathunsmitty** [uclaradio/uclaradio#141]
## Context
Recently, I came across [an issue](https://github.com/facebookincubator/create-react-app/issues/87) where the contributors of create-react-app advocated for dropping `.jsx` extension for the `.js` extension. I started to do this in [a new branch](https://github.com/uclaradio/uclaradio/tree/nathan/rename-jsx-to-js), but then came across a linter error and found that [airbnb prefers use of the `.jsx` syntax](https://github.com/airbnb/javascript/pull/985). I wanted to open it up for discussion of which file extension we want to use. Personally, I'm in the `.js` camp as that seems to be more popular and gaining traction.

**Comment by binerys** [comment]
If it doesn't really affect our build system (looks like webpack will easily handle the `.js` version), I'm with the use of `.js`. Simplicity and consistency is better in the end.
