### ISSUE TITLE
Email Typo in About Page

### ISSUE THREAD

**Issue by binerys** [uclaradio/uclaradio#173]
![image](https://user-images.githubusercontent.com/9737156/32299333-784ec86a-bf12-11e7-8166-1a642cf78910.png)

## Context
There's a typo in our About page! Please change `radio.info@media.ucla.com` to `radio.info@media.ucla.edu`. 

You can find the About page in `client\react\components\AboutPage`

**Comment by derek-palmer** [comment]
```
\client\react\frontpage\components\AboutPage.js
```
is there I found it, is this the correct location? I'll take this issue.

**Comment by binerys** [comment]
fixed by #174
