### ISSUE TITLE
inconsistencies between pages

### ISSUE THREAD

**Issue by zrnorth** [uclaradio/uclaradio#33]
Hey guys, greetings from an alum at Amazon.

I've been digging through the site because of pledge drive and I think many of the features you guys have added are super sick. I remember we really wanted to have a schedule on there and I had to keep telling people "it's too much work" because compilers class was kicking my ass. So that's fucking awesome.

I noticed a couple inconsistencies and I just wanted to point them out because I didn't see issues for them in the backlog.

The main one for me is that the main div padding is inconsistent between different pages. It's most noticable on the header image.

On the main page its 50px, on the /shows pages it is roughly ~70px (I think the header SVG has some padding built in) and the /schedule page has it at 15px.

Also the css on the schedule page seems to be screwed up.

Sorry for all the negativity. The site looks cool and I feel really lucky that my initial, super basic design that I threw together in a caffeine haze has lasted ~ 2 years so far. Getting those button colors to match the background was a fucking nightmare.

**Comment by hsuregan** [comment]
@ChrisLaganiere @nmockovciak either of yall wanna check it out?

**Comment by hsuregan** [comment]
Thanks for letting us know @zrnorth !
