### ISSUE TITLE
Frontpage - DJs List Cleanup

### ISSUE THREAD

**Issue by ChrisLaganiere** [uclaradio/uclaradio#52]
The DJ list is very sleek and looks great but I messed up the layout a bit so there's not enough padding for DJ name labels..

That's a pretty simple fix, but generally I want someone to take one more look and see if there's anyway we can make the layout on this page even more awesome. It's pretty great but spacing between the circles on mobile could be better, for example.

![screen shot 2016-12-15 at 9 23 02 pm](https://cloud.githubusercontent.com/assets/2042745/21252786/ac3ae2b8-c30e-11e6-9322-c41242313cdb.png)

**Comment by ChrisLaganiere** [comment]
Seems to me like we need more spacing on the button of circles and less on top.. Other than that, this tab is pretty sweet and ready to go once we get one more look over

**Comment by kianadk** [comment]
So here's what I've got for now...what do you guys think? Are the circles too close? @nmockovciak is that what you were looking for with the hover behavior? I tried the reverse first where the overlay disappears on hover and it was just way too much white. We could always change how the overlay looks though.

<img width="1280" alt="screen shot 2016-12-20 at 12 41 38 pm" src="https://cloud.githubusercontent.com/assets/10238224/21367127/ba59d452-c6b1-11e6-9080-1d5b1c7681a7.png">
<img width="1280" alt="screen shot 2016-12-20 at 12 41 43 pm" src="https://cloud.githubusercontent.com/assets/10238224/21367130/bb9d3ffc-c6b1-11e6-9c47-7d00604d886d.png">

**Comment by nmockovciak** [comment]
it looks awesome! Good call, I like it as is 👍
