### ISSUE TITLE
Compressing all images stored

### ISSUE THREAD

**Issue by hsuregan** [uclaradio/uclaradio#54]
Images should be compressed to smaller files using **[lwip](https://github.com/EyalAr/lwip)** (a package that was used previously) or any other means necessary.

The reason for this is to prevent people from downloading images that may be on the order of MBs, AND so images aren't so laggy when loading--whether it be on the front page, or the DJs tab--which is poor user experience.

![image](https://cloud.githubusercontent.com/assets/7560478/21621829/5c7e21d4-d1c0-11e6-9939-afebd3738c2b.png)
![image](https://cloud.githubusercontent.com/assets/7560478/21621831/5fd8ff16-d1c0-11e6-9c6e-e2eb0298de22.png)

**Comment by binerys** [comment]
Fixed by #89
