### ISSUE TITLE
DJ Page

### ISSUE THREAD

**Issue by ChrisLaganiere** [uclaradio/uclaradio#58]
Let's set up a single-item DJ page on the new frontpage.

The data should already be there, in the redux store. This should be modeled after the individual show  page, such as `/react/frontpage/containers/ShowContainer.jsx` and `/react/frontpage/components/ShowPage.jsx`
* url should be `/djs/:djName`
* you may want to move `fetchUpdatedDJs:` out of `/containers/DJsTab.jsx` and into `/actions/djs.js`, so you can fetch the list of djs if somebody comes right to `/djs/blueberry` before `/djs`
* any new fields we add to djs should be implemented in the panel... for example right now there's no bio field in panel

**Comment by binerys** [comment]
Fixed by #68
