### ISSUE TITLE
Layout breaks with TuneIn button

### ISSUE THREAD

**Issue by zrnorth** [uclaradio/uclaradio#6]
The layout of the site is wonky on site widths between 768px and 1200px. In bootstrap these are the "Default" and "Portrait Tablet" labels. 

These are pretty common widths among legacy desktops and most tablets. I would think having a correct site width for these, especially the tablet width, would be best.

Here's some pics:

![default](https://cloud.githubusercontent.com/assets/885398/7976241/7f64711e-0a2d-11e5-859d-7c5a052044d0.png)
![portrait_tablet](https://cloud.githubusercontent.com/assets/885398/7976240/7f638858-0a2d-11e5-843d-d038ac82dc39.png)

At first blush I'd suggest just centering and stacking the left buttons and right buttons on these page sizes, a la mobile.

**Comment by hsuregan** [comment]
kk just got around to fixing it
