### ISSUE TITLE
Make the promo banner a carousel

### ISSUE THREAD

**Issue by nathunsmitty** [uclaradio/uclaradio#74]
We have this really cool promo banner at the top of every page that currently displays the show of the month:

<img width="947" alt="screen shot 2017-03-08 at 3 04 41 pm" src="https://cloud.githubusercontent.com/assets/5677971/23728315/09a60aac-0411-11e7-9c79-4417b7162250.png">

Since there's a lot of cool stuff radio does, wouldn't it be cool if we could have the promo banner should multiple images/links?

There are already a lot of carousel plugins out there, so this shouldn't be that hard to do: the key will be integrating it with the rest of the site. Check out [`react/frontpage/Frontpage.jsx`](https://github.com/uclaradio/uclaradio/blob/master/react/frontpage/Frontpage.jsx), the promo banner code is in there.

**Comment by ChrisLaganiere** [comment]
Heads up, we have a slider on the now playing song list. Dunno if it will be useful!

**Comment by binerys** [comment]
Here's the react carousel we are using for the now playing song list! 
https://github.com/akiran/react-slick

I say we go with that instead of using react-bootstrap's carousel

**Comment by ChrisLaganiere** [comment]
I don't see anything wrong with the bootstrap version! Equally valid options
