### ISSUE TITLE
View the Rivendell Master Library in Panel 

### ISSUE THREAD

**Issue by binerys** [uclaradio/uclaradio#76]
![screen shot 2017-03-09 at 1 25 17 am](https://cloud.githubusercontent.com/assets/9737156/23743921/476821b2-0467-11e7-97e8-981be6db2c7c.png)

# Elrond - The Lord of Rivendell
_Name courtesy of @nathunsmitty_

TIL that Rivendell uses a MySQL database and above is a snapshot of the most important table of all - the cart! The cart table features all the songs available in Rivendell. With access to this table, we no longer have to rely on the manually updated [google sheet](https://docs.google.com/spreadsheets/d/1fP6MoxCoc7V8vC79QJbmYJmOlivGPC3-VWfTAGETqhU/edit#gid=0).

Having this data is very exciting because: 

1. DJs will now be able to see whats actually on Rivendell
2. The music department no longer has to manually update the list
3. We'll be able to filter by Artist, Album, Group (Music, NMF, Liner), and of course Titles (no more CTRL+F'ing the google sheet!!) 

# Implementation 

Here's a rough idea that I have so far: 
**EDIT: See update in comment below, leveraging mysql is currently not an option at the moment**
- Utilize the following node mysql package: [mysqljs](https://github.com/mysqljs/mysql)
- Create a separate `db.js`, maybe call it `mysql-db.js`??? This will establish the mysql connection
- Create a `rivendell.js` model in the `database` folder. All this will do is simply query the mysql database for the contents of the Cart table
- Add a route to `routes/panel.js` that will be the GET call for the songs. The song data will be accessible via: `https://uclaradio.com/panel/api/songs`
- Once we have the API route setup, simply build a nice table using the data. I really like Facebook's [FixedDataTable](https://facebook.github.io/fixed-data-table/)

For local dev, I have a SQL dump of the current CART table in Rivendell as of March 8th, 2017 (s/o to Brandon for hooking it up). We can use docker to spin up a MySQL container (which is what I'm currently using) for database access. 

 ## Concerns

Having two different DB's in one repo doesn't sound like best practice, so I was initially thinking of developing this in a separate repo. However, I'd like to take advantage of Panel's current setup, especially since its only accessible by UCLA radio members. 

@hsuregan @ChrisLaganiere Let me know your thoughts on this and any other ideas you have!

**Comment by binerys** [comment]
@kianadk 🙌🏽

**Comment by ChrisLaganiere** [comment]
Daang, awesome find. We could add to the main repo or make another one, depends on implementation.. Your plan looks good to me, with mysql :)

**Comment by binerys** [comment]
# UPDATE TO IMPLEMENTATION
Issues with networking within our station and with Student Media has led to a new game plan. Essentially we have no way of publicly accessing the SQL database hosted on our Rivendell machine. This limits us to only two computers that have rivendell database access: the rivendell machine itself and the rivendell client (in the prod room) 

Here's my new gameplan on getting that precious rivendell data. 

On the rivendell client, run a cron job that will do the following: 
* Connect to the database and obtain an XML dump of our CART table
* Either on the client itself our our server, convert this XML file to JSON (this depends on which machine will do it faster) 
* Upload the XML/JSON file to our server via SFTP -- the rivendell client has SSH access to our server so this will be no problem. 
* The file will be uploaded _daily_ to the server in the following folder `/database`. Daily uploads will occur as it takes a while for the sql database to be exported on the client machine. We'll look into hourly updates in the future

**Comment by binerys** [comment]
Implemented via #103
