### ISSUE TITLE
Pledge Drive Overlay

### ISSUE THREAD

**Issue by binerys** [uclaradio/uclaradio#82]
Add an overlay to the site that reminds people to donate to UCLA Radio's pledge drive. Nina mentioned in the pledge drive meeting that this was very useful as a lot of the links to the pledge drive site came from uclaradio.com. 

Pledge drive promotion starts May 1st, so it needs to be done by then.

**Comment by nmockovciak** [comment]
Hey y'all, how's the splash page going? I just talked to Nina about designing a mockup (or even just implementing a redesign) for the countdown timer, and I was wondering if I could see the splash page at least to see what the current design for it looks like.
 
I wanted to make sure they compliment each other, but also if y'all wanted another opinion on the styling/design of that page too, I'd be down to help out with that too. I just wasn't sure if there's a branch for this? Or where to see your progress?

**Comment by nathunsmitty** [comment]
Splash is currently implemented with some lorem ipsum on the [modal](https://github.com/uclaradio/uclaradio/tree/modal) branch. A design would be great for it! 😄

**Comment by nmockovciak** [comment]
okie, ill look into it! :--)

**Comment by binerys** [comment]
@nmockovciak I'll get the pledge drive graphics A&D showed me!

**Comment by binerys** [comment]
Fixed by Pull #110
