### ISSUE TITLE
Dates appear as NaN/NaN/NaN

### ISSUE THREAD

**Issue by nathunsmitty** [uclaradio/uclaradio#85]
![screen shot 2017-03-17 at 2 53 47 pm](https://cloud.githubusercontent.com/assets/5677971/24064434/b1e43a10-0b21-11e7-9646-f187ac56947e.png)

Seems to be for all posts in the waterfall that aren't at the top. So far only seen it the latest version of Safari, not Chrome.

The relevant file is most likely [`WaterFallContent.jsx`](https://github.com/uclaradio/uclaradio/blob/master/react/frontpage/components/WaterFallContent.jsx). All dates are wrapped in a div with a class of `wf-box-content-text-date`.

**Comment by nathunsmitty** [comment]
This might not be related, but we also might want to look into using the [HTML time tag](https://www.w3schools.com/tags/tag_time.asp) in order to be totally HTML5 savvy.

**Comment by binerys** [comment]
Fixed by #114
