### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by nathunsmitty** [uclaradio/uclaradio#87]
Even though we say the website is totally open source, we don't seem to have a license lol. Is that maybe something we want to add?

[This](https://choosealicense.com) is a pretty good resource for differentiating open source licenses.

**Comment by binerys** [comment]
Good catch lol

What license do you think is best? MIT seems to fit the best for me

**Comment by nathunsmitty** [comment]
I was thinking MIT too! 😁 Great minds think alike

**Comment by binerys** [comment]
MIT license added in PR #88
