### ISSUE TITLE
Show Genre Selector

### ISSUE THREAD

**Issue by nathunsmitty** [uclaradio/uclaradio#97]
## 🚨 BUG FIX 🚨 - DONE
12AM shows are not showing up on schedule :( 

## Pledge Drive: Genre Selector
A suggestion from pledge drive is to highlight shows of different genres! This is similar to how we highlight current show and spotlight of the week. 

## Social Links on Show Pages - DONE
In the grid view, there aren't any social links like there are in the list view 😢.

Grid:
![screen shot 2017-04-05 at 10 10 46 am](https://cloud.githubusercontent.com/assets/5677971/24717689/325972f8-19e8-11e7-9de3-9046558fe35a.png)

List:
![screen shot 2017-04-05 at 10 10 22 am](https://cloud.githubusercontent.com/assets/5677971/24717694/378e577a-19e8-11e7-9e3f-d3e75477d015.png)

Let's just add social links to the bottom of the selected show box in the grid, unless you have an idea for a better spot! 

You'll probably want to take a look at how it's [implemented](https://github.com/uclaradio/uclaradio/blob/master/react/frontpage/components/ShowPage.jsx#L71) and [styled](https://github.com/uclaradio/uclaradio/blob/master/react/frontpage/components/ShowPage.scss#L31) in the list view, see if you can extract those parts out for reusability across the site. A look at [Font Awesome](http://fontawesome.io) (which is where we get the icons from), wouldn't hurt either if you aren't familiar with it.

**Comment by nmockovciak** [comment]
EXPANDED: other things involving Grid view too :-)
- genres by color
- FIX BUG (?) for midnight shows?

**Comment by binerys** [comment]
@nmockovciak thanks for jotting those down! updated the issue description above
